
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/swiper-bundle.css';

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navber";
import NavBar from "@/components/Navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <NavBar></NavBar>
        <main>{children}</main>
      </body>
    </html>
  );
}
